#!/bin/bash
# Sparse gcalcli format, only meeting titles
# Magnus Glantz, sudo@redhat.com, 2020
# Args: <datefrom> <dateto>
# Example dcal 2020-12-03 2020-12-04

# In below file, put
# CLIENTID=
# CLIENTSECRET=
# YEAR=

source ~/.dcal
gcalcli --client-id=$CLIENTID --client-secret=$CLIENTSECRET --calendar $CALENDAR search "meeting" $1 $2 --details all|grep "$YEAR-[0-9][0-9]-[0-9][0-9]"|grep "\- [0-9]"
