- name: Setup VDO
  hosts: all
  vars:
    raw_devices:
      - "/dev/sdb"
    vdo_device: "/dev/sdb1"
    vdo_size: "50g"
    vdo_device_name: "vdotestdevice"
    vdo_write_policy: "async"
  tasks:
    - name: Partition disks with LVM (8e) type
      parted:
        device: "{{ item }}"
        part_type: primary
        flags: [ linux ]
        state: present
        number: 1
        part_start: 0%
        part_end: 100%
      with_items:
        - "{{ raw_devices }}"

    - name: Create VDO device on logical volume
      vdo:
        name: "{{ vdo_device_name }}"
        state: present
        device: "{{ vdo_device }}"
        logicalsize: "{{ vdo_size }}"
        writepolicy: "{{ vdo_write_policy }}"


    - name: Create XFS filesystem on VDO device
      filesystem:
        fstype: xfs
        dev: "/dev/mapper/{{ vdo_device_name }}"

    - name: Mount XFS filesystem
      mount:
        path: "/{{ vdo_device_name}}"
        src: "/dev/mapper/{{ vdo_device_name }}"
        fstype: xfs
        state: mounted
